lista = ("Pão", 4.00, "Carne", 35.90, "Coca-Cola", 7.50,"Queijo", 10.00,"Paçoca", 14.00)
print('--'*15)
print("     Listagem De Preços     ")
print('--'*15)
print(f"{lista[0]}.............R${lista[1]}")
print(f"{lista[2]}...........R${lista[3]}")
print(f"{lista[4]}.......R${lista[5]}")
print(f"{lista[6]}..........R${lista[7]}")
print(f"{lista[8]}..........R${lista[9]}")